services:
  - type: web
    name: newtopdrive
    env: static
    buildCommand: ""
    startCommand: ""
    staticPublicPath: /
    publishPath: .
    routes:
      - path: /
        index: index.html
